name: 🚀 Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup pdm
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11.3
          cache: true
      - run: pdm self list
      - name: Build distributions
        run: pdm build -v
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
